version: 2

registries:
    maven-github:
        type: maven-repository
        url: https://github-package-registry-mirror.gc.nav.no/cached/maven-release
        username: POSTMAN
        password: PAT

updates:

    - package-ecosystem: github-actions
      directory: /
      schedule:
          interval: daily

    - package-ecosystem: gradle
      registries:
        - maven-github
      directory: /
      schedule:
          interval: daily
      groups:
        minor:
          applies-to: version-updates
          exclude-patterns:
            - "no.nav.aap*"
          update-types:
            - "minor"
            - "patch"
        aap:
          patterns:
            - "no.nav.aap*"
        ktor:
          patterns:
            - "*ktor*"

    - package-ecosystem: docker
      directory: /
      schedule:
          interval: daily
