apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: test-token-provider
  namespace: aap
  labels:
    team: aap

spec:
  image: {{ image }}
  port: 8080
  liveness:
    path: /internal/liveness
    initialDelay: 30
    failureThreshold: 10
  readiness:
    path: /internal/readyness
    initialDelay: 30
    failureThreshold: 10
  prometheus:
    enabled: true
    path: /internal/prometheus
  observability:
    autoInstrumentation:
      enabled: true
      runtime: "java"
    logging:
      destinations:
        - id: elastic
        - id: loki
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 50
  resources:
    limits:
      memory: {{ limitsMemory }}
      cpu: {{ limitsCpu }}
    requests:
      memory: {{ requestsMemory }}
      cpu: {{ requestsCpu }}
  maskinporten:
    enabled: true
    scopes:
      consumes:
        - name: "nav:aap:afpprivat.read"
        - name: "nav:aap:afpoffentlig.read"
        - name: "nav:aap:tpordningen.read"
  ingresses:
  {{#each ingresses as |url|}}
     - {{ url }}
  {{/each }}
  secureLogs:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: api
