/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package tokenprovider

import org.junit.jupiter.api.Test


class AppTest {
    @Test
    fun appHasAGreeting() {
        assert(true)
    }
}
